# Generated by Django 5.0.6 on 2024-07-31 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dateBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zarplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dolznosty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Sotrudniki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KadriEntity.sotrudniki')),
                ('Zarplata', models.ManyToManyField(to='KadriEntity.zarplata')),
            ],
        ),
    ]
